### PR TITLE
PdfReader updated for SetUnethicalReading switch

### PR DESCRIPTION
**Pull request by mccbryan3**
Updated Devops test Images and added switch parameter to PdfReader for SetUnethicalReading capabilties

### CODE REVIEW

**Comment by PrzemyslawKlys** [comment]
Are you going to reopen this or should I treat this as you changed your mind on contributing?

**Comment by mccbryan3** [comment]
> Are you going to reopen this or should I treat this as you changed your mind on contributing?

The `SetUnethicalReading` setting doesn't quite do what I expect. This does not seem to be able to read *all* password protected files so it seems misleading. The current version of PSWritePDF gives me errors about password protected files on some files that I have that are not actually password protected and this setting seems to remedy that. I am still trying to figure out what exactly is different with these PDFs . This seems native to the iText7 so I am tyring to figure that out when I have time. 

So.. This is a valid fix for me but not a "IgnorePasswordProtection" cover I think at the moment. The code as requested is complete and ready for the PR but there are these items mentioned.. Any thoughts on this?

Also I could not convert the PR to a draft so I closed it with the thought of reopening.

**Comment by davisdan** [comment]
@mccbryan3 the `SetUnethicalReading` switch doesn't allow reading of PDF files that are password encrypted but will allow reading of PDF files that have password protection/security set (e.g. preventing copying of text etc). It's confusing and obviously in most cases it won't be any use trying to process password encrypted PDF files in a batch. Maybe the option needs to be named `IgnoreProtection` to reduce confusion.

**Comment by PrzemyslawKlys** [comment]
Added and updated docs https://github.com/EvotecIT/PSWritePDF/commit/13b66fb932bbe5927d9a99b07c1c1588c53035e3

Added other stuff as well

**Comment by PrzemyslawKlys** [comment]
Thank you @mccbryan3 for your work! Appreciate it

**Pull request closed without merging**
